### ISSUE TITLE
README should provide an overview and introduction

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/gs-expo-cookiecutter#3]
re: #1, and when #2 is merged, we need the README to provide a high-level overview of this template.

* what is it good for?
* what technical choices have been made, why?
* what are the libraries that are included, and where can you get more information about them?

This README should be adequate to allow a competent new developer (with react/js skills but no react-native experience), who is not at all familiar with our stack, to be able to self-educate themselves to the point that they can become productive using it.

@nntai, can you please prepare this and use @eprikazc as your reviewer (he is our live example "new developer").

**Comment by nntai** [comment]
what should i write in what is it good for section?

**Comment by monkeypants** [comment]
what sort of app can you make from this cookiecutter?

All the apps we have done with this stack (so far) have involved:
 * data collection (potentially offline)
 * "over the air update" capability

@ltankey what would you tell people, when might they want to use this stack?

**Comment by ltankey** [comment]
We can say:

- it is good for data collection through forms
- uses store-and-forward approach for offline first approach
- updates made easy through Expo SDK via OTA update mechanism
- easy to focus on data: what do you want to capture? what do you want to send?
- for more bespoke development (via custom native libraries) it's a good starting point for an "detached" experience (e.g. via ExpoKit)

**Comment by monkeypants** [comment]
and multi-platform (react-native), if you need to support android and ios
